### ISSUE TITLE
oneview_server_profile doesn't work with Python 2.7.13 from RHSCL

### ISSUE THREAD

**Issue by ThomasVitt** [HewlettPackard/python-hpOneView#342]
### Scenario/Intent

I wrote a playbook to deploy a synergy server profile. It worked great until I had to re-install the ansible host. I re-installed the python27 package from the RHSCL repo too and followed the orders to install the oneView python SDK. 

So I thought that I am now using python-2.7.13 instead of the previously installed 2.7.5. 

The following modules are working great: 
- oneview_os_deployment_plan_facts
- oneview_server_profile_facts

But the module oneview_server_profile is crashing: 

fatal: [myhost.local -> localhost]: FAILED! => {
    "changed": false,
    "module_stderr": "/usr/lib/python2.7/site-packages/hpOneView/__init__.py:53: Warning: Running unsupported Python version: 2.7.5, unexpected errors might occur. Use of Python v2.7.9+ is advised.\n  warnings.warn(warning_message % '.'.join(map(str, PYTHON_VERSION)), Warning)\nTraceback (most recent call last):\n  File \"/tmp/ansible_MHyqgH/ansible_module_oneview_server_profile.py\", line 205, in <module>\n    from ansible.module_utils.oneview import (OneViewModuleBase,\nImportError: cannot import name ServerProfileReplaceNamesByUris\n",
    "module_stdout": "",
    "rc": 0
}

The output of ansible --version looks good: 

[ansible@localhost ~]$ ansible --version
ansible 2.4.1.0
  config file = /etc/ansible/ansible.cfg
  configured module search path = [u'/home/ansible/oneview-ansible/library']
  ansible python module location = /usr/lib/python2.7/site-packages/ansible
  executable location = /bin/ansible
  python version = 2.7.13 (default, Feb  8 2017, 06:57:18) [GCC 4.8.5 20150623 (Red Hat 4.8.5-11)]

The Python binary is version 2.7.13: 

[ansible@localhost ~]$ /usr/bin/python --version
Python 2.7.13

What is wrong here? 

### Environment Details
 - **OneView SDK Version:** 4.4.0
 - **OneView Appliance Version:** 3.10.07-0310774
 - **OneView Client API Version:** 500
 - **Python Version:** 2.7.13 from RHSCL
 - **Platform:** RHEL 7.4

### Steps to Reproduce
I don't know how to reproduce it, I installed just the way it is advised in the hpOneView Python SDK site.

### Expected Result
The expected result is that ansible is using the python-2.7.13 binary from the RHSCL

### Actual Result
The actual result is that ansible is using the python-2.7.5 binary from the RHEL 7.4 distro.

**Comment by fgbulsoni** [comment]
Hello @ThomasVitt ,

It seems that the correct repository to open this issue in should've been the [oneview-ansible repository](https://github.com/HewlettPackard/oneview-ansible), as this error is specific to the ansible module, but let's take a stab at it nevertheless.

From the logs you posted there seems to be 2 issues happening in your environment, and one **might** or **might not** be causing the other.

1- As you mentioned, the Python SDK is running from the python 2.7.5 from your system. This is causing the following *warning* message:
```
Warning: Running unsupported Python version: 2.7.5, unexpected errors might occur. Use of Python v2.7.9+ is advised
```
To diagnose this.. 

* How was the Python SDK installed in your system? 

In the README there are a couple of ways shown to do it. It may have been through *pip* or by cloning the github repository.

* Have you tried using the `ansible_python_interpreter` flag when running your playbook to specify the python to be used? 
Something like:

```shell
ansible-playbook -i "localhost," -c local -e 'ansible_python_interpreter=python2.7.13' <your_playbook_path_.yml> -vvv
```

2- I'm also seeing this import error:
```
File "/tmp/ansible_MHyqgH/ansible_module_oneview_server_profile.py", line 205, in \n from ansible.module_utils.oneview import (OneViewModuleBase,\nImportError: cannot import name ServerProfileReplaceNamesByUris\n",
```
This might simply be a side effect of the environment not working properly, but it could also be a second point of worry.

Can you try what has been commented above?

If you can run the playbook with the `-vvv` flag and post the full log through a [Gist](https://gist.github.com/) or [Pastebin](https://pastebin.com/), that could also provide more information.

**Comment by ThomasVitt** [comment]
@fgbulsoni 
Thanks a lot for your answer! Indeed the oneview-ansible modules aren't the problem, I think it's the Python OneView SDK. 

The crazy thing is, that I can't even find the python-2.7.5 binary on my linux host.  !?!?

I've built the OneView SDK with "pip install ." inside the directory which I created by cloning https://github.com/HewlettPackard/python-hpOneView.git. 

I pasted the output of the playbook when running "ansible -vvv" on pastebin: 
https://pastebin.com/M5TPX6Mc

**Comment by fgbulsoni** [comment]
@ThomasVitt Have you tried calling python directly and importing the hpOneView module?

Such as:

```shell
/usr/bin/python -c 'import hponeview'
```

If this works it should not return any output.

You can also try to run a couple of examples from the Python SDK to make sure the SDK is properly setup.

Please also post the outputs of:
```shell
env | grep ANSIBLE
```
and
```
pip -V
```

**Comment by ThomasVitt** [comment]
@fgbulsoni  /usr/bin/python -c 'import hpOneView' does not return any output.   
env | grep ANSIBLE  also returns no output.
pip -V: 
pip 9.0.1 from /opt/rh/python27/root/usr/lib/python2.7/site-packages (python 2.7)

**Comment by fgbulsoni** [comment]
@ThomasVitt I see.

Since nothing is returned from `env | grep ANSIBLE` I'm assuming that the [step 2](https://github.com/HewlettPackard/oneview-ansible#2-configure-the-ansible_library-environmental-variable) from the oneview-ansible modules configuration was probably skipped.

Could you try performing the step linked?

Still unsure as to why you are getting the 2.7.5 version warning though.

**Comment by ThomasVitt** [comment]
@fgbulsoni 
Yes I did miss that step. But now the error message changed:

fatal: [hcap-nprod-01.hpsc.local -> localhost]: FAILED! => {
    "changed": false,
    "module_stderr": "/usr/lib/python2.7/site-packages/hpOneView/__init__.py:53: Warning: Running unsupported Python version: 2.7.5, unexpected errors might occur. Use of Python v2.7.9+ is advised.\n  warnings.warn(warning_message % '.'.join(map(str, PYTHON_VERSION)), Warning)\nTraceback (most recent call last):\n  File \"/tmp/ansible_kzac2t/ansible_module_oneview_server_profile.py\", line 611, in <module>\n    main()\n  File \"/tmp/ansible_kzac2t/ansible_module_oneview_server_profile.py\", line 607, in main\n    ServerProfileModule().run()\n  File \"/tmp/ansible_kzac2t/ansible_modlib.zip/ansible/module_utils/oneview.py\", line 428, in run\n    result = self.execute_module()\n  File \"/tmp/ansible_kzac2t/ansible_module_oneview_server_profile.py\", line 255, in execute_module\n    created, changed, msg, server_profile = self.__present(data, server_profile)\n  File \"/tmp/ansible_kzac2t/ansible_module_oneview_server_profile.py\", line 297, in __present\n    resource = self.__create_profile(data, server_template)\n  File \"/tmp/ansible_kzac2t/ansible_module_oneview_server_profile.py\", line 423, in __create_profile\n    return self.oneview_client.server_profiles.create(server_profile)\n  File \"/usr/lib/python2.7/site-packages/hpOneView/resources/servers/server_profiles.py\", line 66, in create\n    return self._client.create(resource=resource, timeout=timeout, default_values=self.DEFAULT_VALUES)\n  File \"/usr/lib/python2.7/site-packages/hpOneView/resources/resource.py\", line 442, in create\n    return self.__do_post(uri, resource, timeout, custom_headers)\n  File \"/usr/lib/python2.7/site-packages/hpOneView/resources/resource.py\", line 751, in __do_post\n    task, entity = self._connection.post(uri, resource, custom_headers=custom_headers)\n  File \"/usr/lib/python2.7/site-packages/hpOneView/connection.py\", line 366, in post\n    return self.__do_rest_call('POST', uri, body, custom_headers=custom_headers)\n  File \"/usr/lib/python2.7/site-packages/hpOneView/connection.py\", line 393, in __do_rest_call\n    raise HPOneViewException(body)\nHPOneViewException: (u'Unrecognized JSON field.', {u'errorSource': None, u'recommendedActions': [u'Check the valid fields for this JSON object and remove or correct the unrecognized field.'], u'data': {}, u'errorCode': u'UNRECOGNIZED_JSON_FIELD', u'details': u'The field named server_template near line 1, column 466 is not a valid field in this JSON object.', u'message': u'Unrecognized JSON field.', u'nestedErrors': []})\n",
    "module_stdout": "",
    "rc": 0
}

MSG:

MODULE FAILURE

**Comment by fgbulsoni** [comment]
```
(...) 'UNRECOGNIZED_JSON_FIELD', u'details': u'The field named server_template near line 1, column 466 is not a valid field in this JSON object.
```

I'm assuming you have a `server_template` declared in your playbook.

`server_template` was used prior to v5.0.0 to allow specifying a Server Profile Template name instead of URI on a `oneview_server_profile` resource declaration.

It was, however, not following the naming standards enforced across the oneview-ansible modules, so it was fixed in [this commit](https://github.com/HewlettPackard/oneview-ansible/commit/b18d972daede6a9b3c0b85d79ed07b4ea12914b5) to `serverProfileTemplateName`. This info seems to missing from the CHANGELOG, so I'll send in an update for that.

Swapping out `server_template` for `serverProfileTemplateName` in your playbook should fix this issue.


As for the python2.7.5 warnings:
When you ran pip -V, this is the path you got: 
`/opt/rh/python27/root/usr/lib/python2.7/site-packages`
And this is where your ansible says that the hpOneView SDK is at: 
`/usr/lib/python2.7/site-packages/hpOneView/`

I'm assuming the path ansible is mentioning is the system's default, so it does seem that ansible is picking up the wrong version of python when running, and that the hpOneView module is also installed for that version.

Could you try to explicitly specify the python version to be used when running your playbook, and verify if the warnings continue to appear?

Something like:
```
ansible-playbook -e 'ansible_python_interpreter=/usr/bin/python' <your_playbook_path_.yml> -vvv
```
since your /usr/bin/python should resolve to `2.7.13`.

**Comment by ThomasVitt** [comment]
Hey @fgbulsoni,
now it works !! Yes, I had a reference to "server_template". I fixed that, along with the env vars from step 2 of the oneview-ansible manual. 

Thank you so much for your support !!!
